# Settings.yml
---
conf.py:
  project: TypoScript Syntax and In-depth Study
  copyright: 2000-2013
  version: 6.0.0
  release: 6.0.0
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-TyposcriptSyntax
    github_branch: 6-0
  latex_documents:
  - - Index
    - t3tssyntax.tex
    - TypoScript Syntax and In-depth Study
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
